name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.14.0'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create production environment
        run: |
          mkdir -p src/environments

          cat > src/environments/environment.prod.ts <<EOF
          export const environment = {
            production: true,
            SUPABASE_URL: '${{ secrets.SUPABASE_URL }}',
            SUPABASE_KEY: '${{ secrets.SUPABASE_KEY }}'
          };
          EOF

      - name: Build Angular
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
